#!/usr/bin/env ansible-playbook
---
- hosts: webserver
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: deny all
      ufw:
        state: enabled
        policy: deny

    - name: allow ssh on monkeypj
      ufw:
        rule: allow
        name: OpenSSH
        src: 192.186.0.0/24

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '443'
        proto: tcp