#!/usr/bin/env ansible-playbook
---
- hosts: webserver
 
- import_playbook: playbooks/apache2.yml
  vars:
    project_dir: '/home/mweltin/cubs'
    angular_dist_dir: "{{project_dir}}/web/dist/bbhip"
    doc_root: '/var/www/bbhip'
    web_root: '/var/www'
    server_name: 'cubs.mweltin.com'
    user: 'mweltin'
    python_home: '/var/www/venv'  
    python_path: '/var/www:/var/www/api'
    wsgi_file: '/var/www/api/bbhip.wsgi' 
    wsgi_script_alias: '/api'
    cgi_path: '/var/www/api'
    virtual_host: '192.168.0.2'

- import_playbook: playbooks/ufw.yml


